name: PAIN

on:
  push:
    branches: [ "master" ]

jobs:

  buildtest:

    runs-on: ubuntu-latest

    steps:
    - name: JMeter Test
      working-directory: ${{ github.workspace }}
      uses: QAInsights/PerfAction@v3.1
      with:
        test-plan-path: test.jmx
        args: ""
    - name: Upload Results
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-results
        path: result.jtl
